version: '3'

services:
  backEnd:
    build: 
      context: ./
      dockerfile: ./project/docker/DockerfileBackEnd
    image: img_back
    volumes:
      - ./:/mnt/app
    ports:
      - 5555:5555

  frontEnd:
    build:
      context: ./
      dockerfile: ./project/docker/DockerfileFrontEnd
    image: img_front
    volumes:
      - ./:/mnt/app
    ports:
      - 5556:5556
    depends_on:
      - backEnd

  csrf:
    build:
      context: ./
      dockerfile: ./project/docker/DockerfileCSRF
    image: img_csrf
    volumes:
      - ./:/mnt/app
    ports:
      - 5557:5557
    depends_on:
      - backEnd

  xss:
    build:
      context: ./
      dockerfile: ./project/docker/DockerfileXSS
    image: img_xss
    volumes:
      - ./:/mnt/app
    ports:
      - 5558:5558
    depends_on:
      - backEnd